# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20180129_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clusters.Cluster'),
        ),
    ]
