# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_auto_20180129_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='2',
            field=models.IntegerField(default=0, verbose_name='0'),
        ),
    ]
