# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_text_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='2',
        ),
        migrations.AddField(
            model_name='text',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
