# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0007_auto_20180130_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag_Text',
            new_name='TagText',
        ),
        migrations.RemoveField(
            model_name='text',
            name='source_url',
        ),
        migrations.AddField(
            model_name='text',
            name='tonality',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='url',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='texts.Url'),
        ),
    ]
