# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_auto_20180131_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='tonality',
            field=models.IntegerField(default=0),
        ),
    ]
